spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/devoralime
    password: admin

  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 215MB
      file-size-threshold: 2KB
      max-file-size: 200MB
